name: Test and Deploy Lib and FastAPI Service

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  packages: write

jobs:
  test-lib:
    name: 🧪 Test Calculator Lib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build and test tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine pytest

      - name: Install lib locally
        run: |
          python -m pip install .

      - name: Run tests for library
        run: |
          pytest test_lib/

  deploy-lib:
    name: 📦 Publish Calculator Lib to GitHub Packages
    runs-on: ubuntu-latest
    needs: test-lib

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build library
        run: |
          python -m build

      - name: Publish library to GitHub Packages
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m twine upload \
            --repository-url https://upload.pypi.org/legacy/ \
            dist/*

  test-service:
    name: 🧪 Test FastAPI Service
    runs-on: ubuntu-latest
    needs: deploy-lib  # <-- Testar o serviço só depois que a lib foi publicada

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install service dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install calculator-lib

      - name: Run tests for service
        run: |
          pytest tests/

  deploy-service:
    name: 🚀 Build and Push FastAPI Docker Image
    runs-on: ubuntu-latest
    needs: test-service   # <- Só faz o deploy se os testes do serviço passarem

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/fastapi-calculator:latest
